# Generated by Django 2.1.1 on 2018-09-19 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='material_interiores',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_interiores', to='cotizacion.Materiales'),
        ),
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='medida_alto_interiores',
            field=models.FloatField(blank=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='medida_ancho_interiores',
            field=models.FloatField(blank=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
