# Generated by Django 2.1.1 on 2018-09-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_auto_20180919_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='material_interiores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_interiores', to='cotizacion.Materiales'),
        ),
    ]
