# Generated by Django 2.1.1 on 2018-09-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_auto_20180919_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='material_interiores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_interiores', to='cotizacion.Materiales'),
        ),
    ]
