# Generated by Django 2.1.1 on 2018-09-19 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0004_auto_20180919_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='medida_alto_interiores',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='medida_ancho_interiores',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
