# Generated by Django 2.1.1 on 2018-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0005_auto_20180919_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionessolicitadas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\Juan Jose Acaiturri\\Google Drive\\IngrafenApp\\IngrafenApp\\media'),
        ),
    ]
