# Generated by Django 2.1.1 on 2018-10-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_cotizacionessolicitadas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='detalles',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cotizacionessolicitadas',
            name='nombre_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='cotizacion.Clientes'),
        ),
    ]
